PORTNAME=	Neovim-Ext
PORTVERSION=	0.05
CATEGORIES=	editors perl5
MASTER_SITES=	CPAN
MASTER_SITE_SUBDIR=	CPAN:JACQUESG 

PKGNAMEPREFIX=	p5-

MAINTAINER=	dyeske@gmail.com
COMMENT=	perl for nvim

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
