PORTNAME=	gorun
DISTVERSIONPREFIX=	v
DISTVERSION=	1.0.0
CATEGORIES=	devel

MAINTAINER=	dyeske@gmail.com
COMMENT=	Runner for the Go programming language
WWW=		https://github.com/dyeske/gorun

LICENSE=	GPLv3+

USES=		go:modules

USE_GITHUB=	yes
GH_ACCOUNT=	dyeske

PLIST_FILES=	bin/gorun

.include <bsd.port.mk>
