--- pyproject.toml.orig	2023-10-06 12:48:58.000000000 -0400
+++ pyproject.toml	2023-10-11 06:43:33.484219000 -0400
@@ -1,6 +1,6 @@
 [build-system]
 requires = [
-"flit_core>=3.7.1,<3.8.1",
+"flit_core>=3.7.1,<8.8.1",
 ]
 build-backend = "pep517"
 backend-path = ["backends"]
@@ -30,16 +30,16 @@
 dependencies = [
     "colorama>=0.2.5,<0.4.7",
     "docutils>=0.10,<0.20",
-    "cryptography>=3.3.2,<40.0.2",
-    "ruamel.yaml>=0.15.0,<=0.17.21",
+    "cryptography>=3.3.2,<50.0.2",
+    "ruamel.yaml>=0.15.0,<=0.27.21",
     # ruamel.yaml only requires ruamel.yaml.clib for Python versions
     # less than or equal to Python 3.10. In order to ensure we have
     # a consistent dependency closure across all Python versions,
     # we explicitly include ruamel.yaml.clib as a dependency.
-    "ruamel.yaml.clib>=0.2.0,<=0.2.7",
-    "prompt-toolkit>=3.0.24,<3.0.39",
+    "ruamel.yaml.clib>=0.2.0,<=0.3.7",
+    "prompt-toolkit>=3.0.24,<4.0.39",
     "distro>=1.5.0,<1.9.0",
-    "awscrt>=0.16.4,<=0.16.16",
+    "awscrt>=0.16.4,<=0.20.16",
     "python-dateutil>=2.1,<3.0.0",
     "jmespath>=0.7.1,<1.1.0",
     "urllib3>=1.25.4,<1.27",
@@ -98,4 +98,4 @@
 ]
 
 [tool.black]
-line-length = 80
\ No newline at end of file
+line-length = 80
