--- pyproject.toml.orig	2023-06-09 12:26:56.000000000 -0400
+++ pyproject.toml	2023-06-09 20:24:16.301048000 -0400
@@ -1,6 +1,6 @@
 [build-system]
 requires = [
-"flit_core>=3.7.1,<3.8.1",
+"flit_core>=3.7.1,<3.9.9",
 ]
 build-backend = "pep517"
 backend-path = ["backends"]
@@ -31,15 +31,15 @@
     "colorama>=0.2.5,<0.4.7",
     "docutils>=0.10,<0.20",
     "cryptography>=3.3.2,<40.0.2",
-    "ruamel.yaml>=0.15.0,<=0.17.21",
+    "ruamel.yaml>=0.15.0,<=0.17.99",
     # ruamel.yaml only requires ruamel.yaml.clib for Python versions
     # less than or equal to Python 3.10. In order to ensure we have
     # a consistent dependency closure across all Python versions,
     # we explicitly include ruamel.yaml.clib as a dependency.
     "ruamel.yaml.clib>=0.2.0,<=0.2.7",
-    "prompt-toolkit>=3.0.24,<3.0.39",
+    "prompt-toolkit>=3.0.24,<3.0.60",
     "distro>=1.5.0,<1.9.0",
-    "awscrt>=0.12.4,<=0.16.16",
+    "awscrt>=0.12.4,<=0.16.50",
     "python-dateutil>=2.1,<3.0.0",
     "jmespath>=0.7.1,<1.1.0",
     "urllib3>=1.25.4,<1.27",
